### ISSUE TITLE
Bad performance on HoloLens

### ISSUE THREAD

**Issue by SabinMGeorge** [microsoft/MR_RetailExperienceWorkshop#7]
I have followed the tutorial and build the MR_RetailExperienceWorkshop Asset.scene on HL. The first set-up ended with FPS
less than 30Fps

So, I followed the following steps to get better performance

1. Disabled post-processing
      Fps improved a bit
2. Disabled all real-time lights
     Huge improvements. (no idea why used many lights) 
     Still, if you look at 'Rack with bottles' or 'Books rack' corners, the fps drops less than 40

My first impression is all the models are high-poly and look like not made for mobile hardware.

Could you please look into this? or are there any optimized versions available?

Thanks
Sabin M. George

**Comment by mr0ng** [comment]
@SabinMGeorge this issue has been resolved with PR #8 . Thank you for your suggestions!
